### ISSUE TITLE
Missing package at NPM

### ISSUE THREAD

**Issue by Fluzko** [zjxxxxxxxxx/babel-plugin-clsx#1]
The package has been removed from npm and we have some CIs failing. Any chance to review it?

**Comment by zjxxxxxxxxx** [comment]
> The package has been removed from npm and we have some CIs failing. Any chance to review it?

I have reached out to npm to restore this package and they are working on it.

**Comment by zjxxxxxxxxx** [comment]
> The package has been removed from npm and we have some CIs failing. Any chance to review it?

It's back to normal. You can try it.
